In [1]:
import pandas as pd

In [7]:
import sqlite3

In [8]:
import pandas as pd

In [12]:
df = pd.read_csv(r"C:\Users\user\zomato_sql_ready_cleaned_final.csv")

In [13]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost_for_two_people,menu_item,listed_in_type,listed_in_city,cost_category,online_order_flag,table_booking_flag,votes_log
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,[],Buffet,Banashankari,Expensive,1,1,6.654153
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,[],Buffet,Banashankari,Expensive,1,0,6.669498
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,[],Buffet,Banashankari,Expensive,1,0,6.823286
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,[],Buffet,Banashankari,Budget,0,0,4.488636
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,[],Buffet,Banashankari,Affordable,0,0,5.117994

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   url                         51717 non-null  object
 1   address                     51717 non-null  object
 2   name                        51717 non-null  object
 3   online_order                51717 non-null  object
 4   book_table                  51717 non-null  object
 5   rate                        43942 non-null  object
 6   votes                       51717 non-null  int64
 7   phone                       51717 non-null  object
 8   location                    51717 non-null  object
 9   rest_type                   51717 non-null  object
 10  dish_liked                  51717 non-null  object
 11  cuisines                    51717 non-null  object
 12  approx_cost_for_two_people  51717 non-null  float64
 13  menu_item                   51717 non-null  object
 14  listed_in_type              51717 non-null  object
 15  listed_in_city              51717 non-null  object
 16  cost_category               51715 non-null  object
 17  online_order_flag           51717 non-null  int64
 18  table_booking_flag          51717 non-null  int64
 19  votes_log                   51717 non-null  float64
dtypes: float64(2), int64(3), object(15)
memory usage: 7.9+ MB

In [16]:
import sqlite3

# this creates a database file called Zomato_project.db in your current folder

In [17]:
conn = sqlite3.connect("zomato_project.db")

In [20]:
cursor = conn.cursor()

print("SQLite database created and connected!")

SQLite database created and connected!

In [21]:
# Use your loaded CSV (df)
cols = df.columns
# Make all columns TEXT type for simplicity
col_str = ", ".join([f"{col} TEXT" for col in cols])
table_name = "restaurants"

# Remove old table if it exists
cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

# Create new table
cursor.execute(f"CREATE TABLE {table_name} ({col_str})")
print(f"Table '{table_name}' created successfully!")

Table 'restaurants' created successfully!

In [22]:
# Insert all rows from the CSV into the SQLite table
for i, row in df.iterrows():
    sql = f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES ({', '.join(['?']*len(cols))})"
    cursor.execute(sql, tuple(row))

# Save changes
conn.commit()
print("CSV imported into SQLite successfully!")

CSV imported into SQLite successfully!

In [23]:
# Read first 5 rows from SQL
df_sql = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", conn)
df_sql

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost_for_two_people,menu_item,listed_in_type,listed_in_city,cost_category,online_order_flag,table_booking_flag,votes_log
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,[],Buffet,Banashankari,Expensive,1,1,6.65415252018322
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,[],Buffet,Banashankari,Expensive,1,0,6.66949808985788
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,[],Buffet,Banashankari,Expensive,1,0,6.82328612235569
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,[],Buffet,Banashankari,Budget,0,0,4.48863636973214
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,[],Buffet,Banashankari,Affordable,0,0,5.11799381241676

# Total number of restaurants

In [28]:
df_total = pd.read_sql(f"SELECT COUNT(*) AS total_restaurants FROM {table_name};",conn)
df_total

   total_restaurants
0              51717

# Restaurants in a specific area

In [44]:
area_name = 'BTM'
df_area = pd.read_sql(f"SELECT * FROM {table_name} WHERE Location ='{area_name}';",conn)
df_area.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost_for_two_people,menu_item,listed_in_type,listed_in_city,cost_category,online_order_flag,table_booking_flag,votes_log
0,https://www.zomato.com/bangalore/sankranthi-ve...,"986, 1st Block, Vijaya Bank Layout, 4th Stage,...",Sankranthi Veg Restaurant,Yes,No,3.0/5,102,+91 8095275614,BTM,Casual Dining,"Tea, Vada Sambar, Masala Dosa","South Indian, North Indian, Chinese",600.0,"['Jeera Rice', 'Veg Pulao', 'Veg Hyderabadi Bi...",Buffet,Bannerghatta Road,Affordable,1,0,4.63472898822964
1,https://www.zomato.com/bangalore/hearts-unlock...,"18, 3rd Floor, 2nd Cross, NS Palya, Industrial...",Hearts Unlock Cafe,No,No,3.2/5,11,+91 9008143437\r\n+91 7259710298,BTM,Cafe,not mentioned,"Cafe, Healthy Food",500.0,[],Cafes,Bannerghatta Road,Affordable,0,0,2.484906649788
2,https://www.zomato.com/bangalore/eat-fit-btm-b...,"96, 29th Main, 23rd Cross, 2nd Stage, BTM, Ban...",eat.fit,Yes,No,4.5/5,1178,Not Available,BTM,Delivery,"Healthy Breakfast, Salads, Date Pudding, Chick...","Healthy Food, North Indian, Biryani, Continent...",500.0,[],Delivery,Bannerghatta Road,Affordable,1,0,7.07242190053737
3,https://www.zomato.com/bangalore/sai-abhiruchi...,"808, 1st Floor, Above Eye World Optical, 7th C...",Sai Abhiruchi,Yes,No,3.7/5,335,080 49653037,BTM,Casual Dining,"Dum Biryani, Dal Fry, Paneer Biryani","Andhra, North Indian, Biryani",800.0,[],Delivery,Bannerghatta Road,Expensive,1,0,5.8171111599632
4,https://www.zomato.com/bangalore/capsicum-fami...,"774, 3rd Floor, 16th Main, 7th Cross, 2nd Stag...",Capsicum Family Restaurant,Yes,No,3.8/5,254,080 49652641,BTM,Casual Dining,Mutton Biryani,"Biryani, North Indian",800.0,"['Gobi Manchurian', 'Tandoori Chicken', 'Phulk...",Delivery,Bannerghatta Road,Expensive,1,0,5.54126354515843

# Count of restaurants by cuisine

In [64]:
df_cuisine = df.groupby('cuisines').size().reset_index(name='count').sort_values(by='count',ascending=False)
df_cuisine.head(15)

                                 cuisines  count
1823                         North Indian   2958
1898                North Indian, Chinese   2385
2463                         South Indian   1828
403                               Biryani    918
271                      Bakery, Desserts    911
1256                            Fast Food    803
1194                             Desserts    766
579                                  Cafe    756
2561  South Indian, North Indian, Chinese    726
260                                Bakery    651
816                               Chinese    556
1498                  Ice Cream, Desserts    417
907                 Chinese, North Indian    415
1760                  Mithai, Street Food    372
1219                  Desserts, Ice Cream    354

# Restaurants serving a specific cuisine

In [68]:
cuisine_name = 'South Indian, North Indian, Chinese'
df_cuisine_area = pd.read_sql(f"""SELECT Name, Location, listed_in_city FROM {table_name}
WHERE cuisines LIKE '%{cuisine_name}%';""",conn)
df_cuisine_area.head(15)

                          name            location listed_in_city
0   Vi Ra's Bar and Restaurant        Banashankari   Banashankari
1       Bengaluru Coffee House        Banashankari   Banashankari
2                 Anna Kuteera        Banashankari   Banashankari
3           Sri Udupi Food Hub           Jayanagar   Banashankari
4                 Sagar Deluxe  Kumaraswamy Layout   Banashankari
5         Donne Biriyani House        Banashankari   Banashankari
6                  Udupi Ruchi        Banashankari   Banashankari
7    A2B - Adyar Ananda Bhavan         Mysore Road   Banashankari
8            Srikrishna Bhavan        Banashankari   Banashankari
9   Karavali Family Restaurant           Jayanagar   Banashankari
10               Shanthi Sagar         Uttarahalli   Banashankari
11           Udupi Ruchi Grand        Banashankari   Banashankari
12                 Matru Sagar        Banashankari   Banashankari
13                 South Grand         Uttarahalli   Banashankari
14               Dakshin Grand        Banashankari   Banashankari